# Generated by Django 3.1 on 2020-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_policy',
            fields=[
                ('policy_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('policy_cname', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('1', 'Motor'), ('2', 'Health'), ('3', 'Travel')], max_length=20)),
                ('policy_start', models.DateField()),
                ('policy_expire', models.DateField()),
                ('policy_amt', models.FloatField()),
            ],
        ),
    ]
