# Generated by Django 3.1 on 2020-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_policy',
            options={'verbose_name': 'Policy List'},
        ),
        migrations.AddField(
            model_name='data_policy',
            name='policy_status',
            field=models.BooleanField(default=True, verbose_name='Policy Status'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_amt',
            field=models.FloatField(verbose_name='Policy Amount'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_cname',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_expire',
            field=models.DateField(verbose_name='Policy End Date'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_no',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Policy No'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_start',
            field=models.DateField(verbose_name='Policy Start Date'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_type',
            field=models.CharField(choices=[('1', 'Motor'), ('2', 'Health'), ('3', 'Travel')], max_length=20, verbose_name='Policy Type'),
        ),
    ]
