# Generated by Django 3.1 on 2020-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyapi', '0002_auto_20200819_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_policy',
            name='policy_auto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_no',
            field=models.BigIntegerField(verbose_name='Policy No'),
        ),
        migrations.AlterField(
            model_name='data_policy',
            name='policy_type',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Health', 'Health'), ('Travel', 'Travel')], max_length=20, verbose_name='Policy Type'),
        ),
    ]
